project_dir: "/opt/coin"
compose_project_name: "coin"
main_domain: bonavii.com
domains:
  - name: api.bonavii.com
    port: 8080
    basic_auth: false

  - name: api.dev.bonavii.com
    port: 8081
    basic_auth: false
