apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  PGSQL_HOST: "postgres-postgresql.postgres-{{ .Values.environment }}.svc.cluster.local:5432"
  OTLP_IS_ENABLED: "false"
  OTLP_HTTP_ENDPOINT: ""
  OTLP_INSECURE: "false"
  SERVICE_NAME: "coin"
  ENVIRONMENT: "{{ .Values.environment }}"
  TG_BOT_ENABLED: "{{ .Values.coin_server.tg_bot_enabled }}"
  STACK_TRACE_ENABLED: "true"
  LOG_LEVEL: "debug"
  LOG_FORMAT: "json"
  LISTEN_HTTP: "0.0.0.0:8080"
  PORT_HTTP: "0.0.0.0:8080"
  PORT_GRPC: "0.0.0.0:8090"
  AUTH_REFRESH_TOKEN_TTL: "720h"
  AUTH_ACCESS_TOKEN_TTL: "500h"
  NOTIFICATIONS_ENABLED: "false"
  NOTIFICATIONS_APNS_KEY_FILE_PATH: "certs/APNsKey.p8"
