apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  PGSQL_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  PGSQL_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote}}
  PGSQL_DATABASE: {{ .Values.postgresql.auth.database | b64enc | quote}}
  AUTH_TOKEN_SIGNING_KEY: {{ .Values.coin_server.auth.key | b64enc | quote}}
  SHA_SALT: {{ .Values.coin_server.auth.salt | b64enc | quote}}
  TG_BOT_TOKEN: {{ .Values.coin_server.telegram_bot.token | b64enc | quote}}
  TG_CHAT_ID: {{ .Values.coin_server.telegram_bot.chat_id | b64enc | quote}}
  API_KEY_CURRENCY_PROVIDER: {{ .Values.coin_server.api_key_currency_provider | b64enc | quote}}
  NOTIFICATIONS_APNS_TEAM_ID: {{ .Values.coin_server.apns.team_id | b64enc | quote}}
  NOTIFICATIONS_APNS_KEY_ID: {{ .Values.coin_server.apns.key_id | b64enc | quote}}
