postgresql:
    auth:
        password: ENC[AES256_GCM,data:lqzLIEqeOrLW/+qeDI1xwf9o/6A=,iv:xUNFm2yThofM45XIK9nGT5VuabIaaLtc+jt1y24XKv4=,tag:guhKZWj0VBzUIoD7UpLjlg==,type:str]
        username: ENC[AES256_GCM,data:IfwW9A==,iv:uo0BYBy9TwZ3N0wgVgYLM9DOUdMpctGA3fB87v07EM4=,tag:fCpP1SmzMAyEQkbDERqaFA==,type:str]
        database: ENC[AES256_GCM,data:GGwEHA==,iv:P6nBIjFSFv5kidgZxdpaZSG3e6bWPHCOjQH+BTv6NMw=,tag:QDmSmOCJaJabqKfMWsJMng==,type:str]
coin_server:
    auth:
        salt: ENC[AES256_GCM,data:jBNPr0yI1uxZbigb2jwf8HMVXw==,iv:ZO1Y95zzLjW+9hONmt3C2foDuhJlFHfKHt7Kf8NWy8Y=,tag:Nufvh+f/uH5HM8dbtoRLJQ==,type:str]
        key: ENC[AES256_GCM,data:7gPiwMl7i35tNbdNv85AKvZql8o+rGVL9pbSdJog5g==,iv:wN4e0HqPSJX6LBW1EWeScZxSPEC5LkXNl1Et+LryRz0=,tag:zSV+PE2tY3r1+H9QPvFmaw==,type:str]
    telegram_bot:
        token: ENC[AES256_GCM,data:hXQszGQhMhYeRxbqBhB46/z5dpX4aNZiSweJf0M2twRFrCO5VX40AlYqIJFFOg==,iv:p/7uWAnn/WkN1DYWS8bObnZ81wiH32fBK2EblKO1CL0=,tag:MLSiud8FMA2Jo3fa6NDD0w==,type:str]
        chat_id: ENC[AES256_GCM,data:G/oXW5QAPm3aQqtQrl4=,iv:TVmaThEwxnHR+hz4evhYNNGxXgBAaDrdb8okf9QK6RU=,tag:RpluorE34hnpdXyleGpSgQ==,type:str]
    api_key_currency_provider: ENC[AES256_GCM,data:KBCBHmCb2qRwAcQnrNohDg2EUjdRGdfsLjGnIAkcBNbSHPdpTcyF2g==,iv:mocDJsK415Eoy7inrkKV+Nzb5PSxJbJMyN3mNvTxxo4=,tag:KBTg5pxCbi9wI2H1QDXQQQ==,type:str]
    apns:
        team_id: ENC[AES256_GCM,data:rGsQspNfXBJO3g==,iv:XF0aXxU5Bc0/f2UQutRmCpjyz9/zXJfNnih1/Hj7dE8=,tag:SfmaCr3kot7ohp8PeINoxA==,type:str]
        key_id: ENC[AES256_GCM,data:c0y/vfFlwbJrWw==,iv:a0mkgaMn+8qHOoFMrKiGIFaxlGnk/7Ch+yl+Suf+0h4=,tag:1dE9/AuIrkABG0BwQzpM3w==,type:str]
    host: ENC[AES256_GCM,data:EOmLuFquHSw8bNS+bHgZ,iv:EnzbJ77YWVjz0yqdo7Xwr+EsonixhOMT60MDoijfQrk=,tag:hZz5o9hEkynSb0eq0Sk7LQ==,type:str]
sops:
    age:
        - recipient: age1l8t7aweckzrjkaxj998n0th5wvp6kmzjpcazt770uupe67cvhscqnpahda
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a1cxS3hLVkFvOVhSUDQ5
            SStseGZnQWZGNUZESlllYlpKOEdJUnRUTTA0CjFLWHMvTnBYM2R2VmljajRlN0h2
            TngxMjJHNGpqeURMdXUwb1NRUGZ2OGcKLS0tICtaWXA0eEdQUndPcVVGMTRCRGk2
            d2dGcGlkc0lLNS95QkxXd3dydHZ2Nm8KycBkJ8eQNPMP5QHSe1ZzPYnFpYbJtV3P
            bwpTBC6kkLuRfCv2KPoF951ZIZZ1k+GXEPu9W20JV2wfTQx+QkG45w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T05:48:33Z"
    mac: ENC[AES256_GCM,data:mmWzVD18LV5QNO1x3+lWnBGiWOZx1gJPJ42XFfYHX2YdKJh35i+ZxgeXsEpYFFqMkgMlxgOb+dXdJ1L42FcvnPBQz2BSFFuhwC09+pKcx06gS0wFZL49BWT3bNg7NBcSwcfgZ7f+7jx/mQBw8vHgCIYmy1hjhO85mfRnU8pc4mE=,iv:wz86tnOAihK7CULZU8zhqg3O6rOTXtfhjUreyNQdn6U=,tag:D6sRZ9euXW6dz3IyIH2M3g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
