postgresql:
    auth:
        password: ENC[AES256_GCM,data:+rayPI4KDaX895UAhzKqFEpUD+0=,iv:UXBYS9ZrAm4LEM6k8IUU072rhNxlD4mk4Cl3+F1qj5M=,tag:sOF2rpW2YJo2V3hVcR6Dpg==,type:str]
        username: ENC[AES256_GCM,data:Wk9fVA==,iv:xqbAmgvvQRmi3GCO9q/9Ue6YbEMeWPKmXGfJcR1MABQ=,tag:/Hga/v3nz4T151hBVbW3nw==,type:str]
        database: ENC[AES256_GCM,data:0bci2w==,iv:cX+v6Gb16phUGrR7i8fzEv40u+tcA3s9Vd1xyKgB5Zg=,tag:KsxIMUssr9c+a3RRID2PxQ==,type:str]
coin_server:
    auth:
        salt: ENC[AES256_GCM,data:BaTP8s9P9dX04VM0bECYbJqyeWI=,iv:lkaki2XQ7u4q7wEaNQUdWrQV0tIjM+qiUHzWcyxBbZQ=,tag:pc+Lpd9on0UqJa/MwEZg5A==,type:str]
        key: ENC[AES256_GCM,data:ede7i5DFiYcqELkr/3pv/7+2TiwMe3yXWmVzx/u+RQ==,iv:PyyBV7UCWJ2gvCI1f/l0AsM/6baqryHpAwTyQHlk5nQ=,tag:pXHxQxp2ggikaTs+pIUS6g==,type:str]
    telegram_bot:
        token: ""
        chat_id: ENC[AES256_GCM,data:yA==,iv:BwBSNsXEPCT2f/O7W2YXJVul3QEMhHBzZNcKNd7KbQk=,tag:Xsw9lGnbek0MFfx+UvqCVQ==,type:str]
    api_key_currency_provider: ENC[AES256_GCM,data:dwcjFbGlDYb2ZkuQS/F+Va+aB2FUdL7k1/eIRo5e+VAYTp82+X7Z6g==,iv:QOIO8w88xP8b7XEZNx6dbKr8Eb3mOjWsONxbrt/XwOM=,tag:Io/Xi4IgGVgmOmt+vDGtZg==,type:str]
    apns:
        team_id: ""
        key_id: ""
    host: ENC[AES256_GCM,data:muwniCcuWCzjtTr3HskJcAkbIw==,iv:2OidPZNbkKN4744ch0PIvB6p9oM/9XwNnt+WrOgqiiw=,tag:nSpvPYKqa9XajGQ75GOY5g==,type:str]
imageCredentials:
    registry: ENC[AES256_GCM,data:J+Ef+ujmWQ==,iv:sHN8eFLExeTQBzRKBd4GhzF4+2gxuViXcd6Vw253hMw=,tag:IW/xgyvTMCzpLLByWh3KVg==,type:str]
    username: ENC[AES256_GCM,data:beE83wIM,iv:v0lfOvg0i57Zv8gEtMuTpbaGRHxJ3dBtJzT0vVh+HR4=,tag:dtvHInjzLnW7Uj2zZqCiAA==,type:str]
    password: ENC[AES256_GCM,data:V1APP9IyJgEATT8lv/jvYsGmTRYQ60RrMjg/Zg3V0YCN0GrroFEXJg==,iv:MsQFI+oWb4pp7fsTx8EOCQYTswBXNi0uPUbAavqTpwo=,tag:QOETb+FwOrXiwruUakns4w==,type:str]
sops:
    age:
        - recipient: age1l8t7aweckzrjkaxj998n0th5wvp6kmzjpcazt770uupe67cvhscqnpahda
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a1cxS3hLVkFvOVhSUDQ5
            SStseGZnQWZGNUZESlllYlpKOEdJUnRUTTA0CjFLWHMvTnBYM2R2VmljajRlN0h2
            TngxMjJHNGpqeURMdXUwb1NRUGZ2OGcKLS0tICtaWXA0eEdQUndPcVVGMTRCRGk2
            d2dGcGlkc0lLNS95QkxXd3dydHZ2Nm8KycBkJ8eQNPMP5QHSe1ZzPYnFpYbJtV3P
            bwpTBC6kkLuRfCv2KPoF951ZIZZ1k+GXEPu9W20JV2wfTQx+QkG45w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T05:54:08Z"
    mac: ENC[AES256_GCM,data:iWyy3BubD4stKL+tJb/SmQHSwRaAZlFXDrc8NJ7VxdUQT9te1G0PtC6/MAeEI/d2NalNjLJnoxM+wws996qswTA2oosoOxJqe4nmnB2EdYZawoyO1d1NxQaGLPwwD5UNfqEpFTmPlHgUsO1HtNa/6JI9q3waO+xzBiWSZM6S5L4=,iv:q0hntXFAJeAuV6MMMWb1XYhHt49ykAKB4dJnWEtgHzU=,tag:ck/2hdT5OzEETDLJ7EwMcA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
