postgresql:
  primary:
    persistence:
      size: 5Gi
      storageClass: "local-path"

coin_server:
  replicas: 1
  image:
    repository: ghcr.io/finfix/go-server-dev
    tag: latest
  telegram_bot:
    enabled: false
