version: "3.13"

services:
  pgsql-dev:
    image: wodby/postgres
    networks:
      - internal
    restart:
      unless-stopped
    ports:
      - "127.0.0.1:5433:5432"
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "2"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-dev:/var/lib/postgresql/data

volumes:
  postgres-dev:

networks:
  internal:
    external: true
