---
- hosts: coin
  become: yes

  vars_files:
    - secrets.yml
    - env.yml

  roles:
    - role: project-environment
    - role: docker
    - role: docker-environment
    - role: nginx
    - role: pgsql
    - role: pgsql-dev
    - role: go-server
    - role: go-server-dev
